export const COMMON_COMMANDS: string[] = [
  "cd ",
  "ls -la",
  "cat ",
  "tail -f ",
  "grep -r ",
  "find . -name ",
  "df -h",
  "du -sh ",
  "free -m",
  "top",
  "htop",
  "ps aux",
  "kill -9 ",
  "systemctl status ",
  "systemctl restart ",
  "journalctl -u ",
  "docker ps",
  "docker logs -f ",
  "docker compose up -d",
  "git status",
  "git pull",
  "git log --oneline",
  "sudo ",
  "chmod +x ",
  "chown -R ",
  "tar -xzf ",
  "curl -fsSL ",
  "wget ",
];
