import type {
  ThemeAppearance,
  ThemeDefinition,
  ThemeFamilyDefinition,
  ThemeMode,
  ThemePreference,
} from "./types";

const draculaLight: ThemeDefinition = {
  id: "dracula-light",
  familyId: "dracula",
  name: "Dracula Light",
  appearance: "light",
  colors: {
    background: "#faf9f7",
    foreground: "#272630",
    surface: "#f0eeed",
    surfaceForeground: "#282a36",
    popover: "#ffffff",
    popoverForeground: "#282a36",
    card: "#ffffff",
    cardForeground: "#282a36",
    primary: "#6940a6",
    primaryForeground: "#ffffff",
    link: "#55409a",
    secondary: "#eae6ed",
    secondaryForeground: "#3d334f",
    muted: "#eeebef",
    mutedForeground: "#625e69",
    accent: "#e7dcf2",
    accentForeground: "#43266f",
    destructive: "#b52646",
    destructiveForeground: "#ffffff",
    danger: "#a71839",
    success: "#18733a",
    warning: "#765400",
    info: "#275d96",
    border: "#d4ced7",
    input: "#aaa1b3",
    ring: "#7650b4",
    listHover: "#efebef",
    listActive: "#e5d8f2",
    listActiveForeground: "#40236d",
  },
  terminal: {
    background: "#fbfbf7",
    foreground: "#282a36",
    cursor: "#6d3fb5",
    selectionBackground: "#ddd2ef",
    black: "#282a36",
    red: "#b52646",
    green: "#18733a",
    yellow: "#765400",
    blue: "#275d96",
    magenta: "#6d3fb5",
    cyan: "#08717a",
    white: "#dedde1",
    brightBlack: "#65616f",
    brightRed: "#d13b5a",
    brightGreen: "#278a4b",
    brightYellow: "#966d08",
    brightBlue: "#3975b5",
    brightMagenta: "#895dcc",
    brightCyan: "#138994",
    brightWhite: "#171820",
  },
};

const draculaDark: ThemeDefinition = {
  id: "dracula-dark",
  familyId: "dracula",
  name: "Dracula Dark",
  appearance: "dark",
  colors: {
    background: "#252631",
    foreground: "#f8f8f2",
    surface: "#1d1e27",
    surfaceForeground: "#f8f8f2",
    popover: "#333542",
    popoverForeground: "#f8f8f2",
    card: "#2c2e3a",
    cardForeground: "#f8f8f2",
    primary: "#bd93f9",
    primaryForeground: "#282a36",
    link: "#8be9fd",
    secondary: "#383a49",
    secondaryForeground: "#f1f1ec",
    muted: "#31333f",
    mutedForeground: "#b1b4c8",
    accent: "#424554",
    accentForeground: "#ffffff",
    destructive: "#c73857",
    destructiveForeground: "#ffffff",
    danger: "#ff6e87",
    success: "#50fa7b",
    warning: "#f1fa8c",
    info: "#8be9fd",
    border: "#414452",
    input: "#62667a",
    ring: "#bd93f9",
    listHover: "#30323e",
    listActive: "#4a3d65",
    listActiveForeground: "#ffffff",
  },
  terminal: {
    background: "#282a36",
    foreground: "#f8f8f2",
    cursor: "#f8f8f2",
    selectionBackground: "#44475a",
    black: "#21222c",
    red: "#ff5555",
    green: "#50fa7b",
    yellow: "#f1fa8c",
    blue: "#6272a4",
    magenta: "#bd93f9",
    cyan: "#8be9fd",
    white: "#f8f8f2",
    brightBlack: "#6272a4",
    brightRed: "#ff6e6e",
    brightGreen: "#69ff94",
    brightYellow: "#ffffa5",
    brightBlue: "#7b8dc1",
    brightMagenta: "#d6acff",
    brightCyan: "#a4ffff",
    brightWhite: "#ffffff",
  },
};

const midnightLight: ThemeDefinition = {
  id: "midnight-light",
  familyId: "midnight",
  name: "Midnight Light",
  appearance: "light",
  colors: {
    background: "#f7f8fb",
    foreground: "#1c2638",
    surface: "#edf0f5",
    surfaceForeground: "#1c2638",
    popover: "#ffffff",
    popoverForeground: "#1c2638",
    card: "#ffffff",
    cardForeground: "#1c2638",
    primary: "#315dad",
    primaryForeground: "#ffffff",
    link: "#2455a3",
    secondary: "#e2e7ef",
    secondaryForeground: "#263852",
    muted: "#e7ebf1",
    mutedForeground: "#586579",
    accent: "#dbe4f2",
    accentForeground: "#214574",
    destructive: "#b4232d",
    destructiveForeground: "#ffffff",
    danger: "#a61b29",
    success: "#1c754a",
    warning: "#765100",
    info: "#235ea7",
    border: "#c5cedb",
    input: "#9daabd",
    ring: "#3e69bd",
    listHover: "#e5eaf1",
    listActive: "#d7e3f6",
    listActiveForeground: "#204c91",
  },
  terminal: {
    background: "#fbfcfe",
    foreground: "#253047",
    cursor: "#3659a7",
    selectionBackground: "#cfdbf2",
    black: "#283248",
    red: "#b4232d",
    green: "#1c754a",
    yellow: "#765100",
    blue: "#2856a8",
    magenta: "#754fa1",
    cyan: "#176c75",
    white: "#d7deea",
    brightBlack: "#667186",
    brightRed: "#d13c45",
    brightGreen: "#2b915d",
    brightYellow: "#976d0a",
    brightBlue: "#416fc0",
    brightMagenta: "#9067bb",
    brightCyan: "#258792",
    brightWhite: "#141c2c",
  },
};

const midnightDark: ThemeDefinition = {
  id: "midnight-dark",
  familyId: "midnight",
  name: "Midnight Dark",
  appearance: "dark",
  colors: {
    background: "#171b28",
    foreground: "#edf1f7",
    surface: "#1e2332",
    surfaceForeground: "#edf1f7",
    popover: "#2a3042",
    popoverForeground: "#f5f7fb",
    card: "#242a3b",
    cardForeground: "#edf1f7",
    primary: "#3472c7",
    primaryForeground: "#ffffff",
    link: "#86b6f8",
    secondary: "#2d3448",
    secondaryForeground: "#e5e8f3",
    muted: "#282e40",
    mutedForeground: "#abb3c3",
    accent: "#343c51",
    accentForeground: "#f5f6fb",
    destructive: "#b94350",
    destructiveForeground: "#ffffff",
    danger: "#ff929d",
    success: "#73cf9b",
    warning: "#e7bd6d",
    info: "#83b5f4",
    border: "#394156",
    input: "#525d76",
    ring: "#79aaf0",
    listHover: "#272d3e",
    listActive: "#344663",
    listActiveForeground: "#ffffff",
  },
  terminal: {
    background: "#12141f",
    foreground: "#e1e4ee",
    cursor: "#80aef5",
    selectionBackground: "#334e7b",
    black: "#242739",
    red: "#ee7d85",
    green: "#70c59a",
    yellow: "#e3b967",
    blue: "#7da7f2",
    magenta: "#b49bdd",
    cyan: "#71c1cc",
    white: "#c3ccdd",
    brightBlack: "#71809a",
    brightRed: "#ff9aa1",
    brightGreen: "#8bd6af",
    brightYellow: "#efcc83",
    brightBlue: "#9bc0f8",
    brightMagenta: "#c9b2eb",
    brightCyan: "#8dd4dd",
    brightWhite: "#f3f6fc",
  },
};

const graphiteLight: ThemeDefinition = {
  id: "graphite-light",
  familyId: "graphite",
  name: "Graphite Light",
  appearance: "light",
  colors: {
    background: "#f8f9f9",
    foreground: "#22282d",
    surface: "#eceff0",
    surfaceForeground: "#22282d",
    popover: "#ffffff",
    popoverForeground: "#22282d",
    card: "#ffffff",
    cardForeground: "#22282d",
    primary: "#3b596f",
    primaryForeground: "#ffffff",
    link: "#315f82",
    secondary: "#e3e7e9",
    secondaryForeground: "#303b44",
    muted: "#e8ebed",
    mutedForeground: "#5d6870",
    accent: "#dbe2e5",
    accentForeground: "#263947",
    destructive: "#ad2831",
    destructiveForeground: "#ffffff",
    danger: "#a31e28",
    success: "#337342",
    warning: "#745100",
    info: "#35628c",
    border: "#cbd2d6",
    input: "#a1adb5",
    ring: "#4e718b",
    listHover: "#e8ecee",
    listActive: "#d9e4e9",
    listActiveForeground: "#304f65",
  },
  terminal: {
    background: "#fcfcfd",
    foreground: "#2c3339",
    cursor: "#3f586e",
    selectionBackground: "#d7e1e7",
    black: "#30363b",
    red: "#ad2831",
    green: "#337342",
    yellow: "#745100",
    blue: "#35628c",
    magenta: "#6e5683",
    cyan: "#286d73",
    white: "#dce1e4",
    brightBlack: "#69737b",
    brightRed: "#cb3e46",
    brightGreen: "#4c8c59",
    brightYellow: "#956d0b",
    brightBlue: "#4d7ba5",
    brightMagenta: "#866a99",
    brightCyan: "#3c858b",
    brightWhite: "#1c2227",
  },
};

const graphiteDark: ThemeDefinition = {
  id: "graphite-dark",
  familyId: "graphite",
  name: "Graphite Dark",
  appearance: "dark",
  colors: {
    background: "#121416",
    foreground: "#e8ebed",
    surface: "#191c1f",
    surfaceForeground: "#e8ebed",
    popover: "#24292d",
    popoverForeground: "#f2f4f5",
    card: "#1f2327",
    cardForeground: "#e8ebed",
    primary: "#4f7188",
    primaryForeground: "#ffffff",
    link: "#7fb3d1",
    secondary: "#272c30",
    secondaryForeground: "#e1e5e7",
    muted: "#23272b",
    mutedForeground: "#a7afb4",
    accent: "#30373c",
    accentForeground: "#f2f4f5",
    destructive: "#b74448",
    destructiveForeground: "#ffffff",
    danger: "#ff898b",
    success: "#82c88a",
    warning: "#e4ba68",
    info: "#80b2dc",
    border: "#373e43",
    input: "#515b62",
    ring: "#7fb3d1",
    listHover: "#22272a",
    listActive: "#304653",
    listActiveForeground: "#f4f8fa",
  },
  terminal: {
    background: "#0d0f10",
    foreground: "#dce1e3",
    cursor: "#7fb3d1",
    selectionBackground: "#344d5b",
    black: "#23272b",
    red: "#ed7c80",
    green: "#82c88a",
    yellow: "#e4ba68",
    blue: "#80b2dc",
    magenta: "#b5a0c3",
    cyan: "#79bdc1",
    white: "#c7ced1",
    brightBlack: "#747e84",
    brightRed: "#ff999b",
    brightGreen: "#9bd7a2",
    brightYellow: "#f0cd85",
    brightBlue: "#9bc7eb",
    brightMagenta: "#c9b6d3",
    brightCyan: "#94d0d3",
    brightWhite: "#f2f4f5",
  },
};

export const THEME_FAMILIES: readonly ThemeFamilyDefinition[] = [
  {
    id: "midnight",
    name: "Midnight",
    description: "Focused navy for terminal work",
    themes: { light: midnightLight, dark: midnightDark },
  },
  {
    id: "graphite",
    name: "Graphite",
    description: "Neutral gray with crisp hierarchy",
    themes: { light: graphiteLight, dark: graphiteDark },
  },
  {
    id: "dracula",
    name: "Dracula",
    description: "Deep purple with vivid terminal accents",
    themes: { light: draculaLight, dark: draculaDark },
  },
];

export const THEMES: readonly ThemeDefinition[] = THEME_FAMILIES.flatMap(
  (family) => [family.themes.light, family.themes.dark],
);

export const DEFAULT_THEME_FAMILY_ID = "midnight";
export const DEFAULT_THEME_MODE: ThemeMode = "dark";
export const DEFAULT_THEME_ID = midnightDark.id;

const LEGACY_THEME_IDS: Readonly<Record<string, string>> = {
  "github-dark": "midnight-dark",
  "dark-modern": "midnight-dark",
  "one-dark-pro": "graphite-dark",
  "one-dark": "graphite-dark",
  dracula: "dracula-dark",
  "tokyo-night": "midnight-dark",
  "github-light": "midnight-light",
  "light-modern": "midnight-light",
  "catppuccin-latte": "dracula-light",
  "solarized-light": "dracula-light",
};

export function getTheme(id: string | null | undefined): ThemeDefinition {
  const resolvedId = id ? (LEGACY_THEME_IDS[id] ?? id) : DEFAULT_THEME_ID;
  return THEMES.find((theme) => theme.id === resolvedId) ?? midnightDark;
}

export function getThemeFamily(
  id: string | null | undefined,
): ThemeFamilyDefinition {
  return THEME_FAMILIES.find((family) => family.id === id) ?? THEME_FAMILIES[0];
}

export function resolveTheme(
  preference: ThemePreference,
  systemAppearance: ThemeAppearance,
): ThemeDefinition {
  const appearance =
    preference.mode === "system" ? systemAppearance : preference.mode;
  return getThemeFamily(preference.familyId).themes[appearance];
}

export function preferenceFromThemeId(id: string): ThemePreference {
  const theme = getTheme(id);
  return { familyId: theme.familyId, mode: theme.appearance };
}
